# version: '3.8'

# services:
#   web:
#     build: .
#     ports:
#       - "5000:5000"   # Change if app runs on a different port
#     volumes:
#       - .:/app
#     depends_on:
#       - redis

#   redis:
#     image: redis:alpine

# version: '3.8'

# services:
#   web:
#     build: .
#     ports:
#       - '5000:5000'
#     volumes:
#       - .:/app

version: '3.8'

services:
  app:
    build: .
    ports:
      - '3000:3000'
    volumes:
      - .:/app
      - /app/node_modules # Prevents overwriting node_modules
    environment:
      - NODE_ENV=development
